### ISSUE TITLE
Middle Name Can Be Removed From Mandatory Field 

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#10]
In Edit Occupant page middle name field can be removed from mandatory field. Because all customers did't have middle name. 
![2018-05-09 14_50_19-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/39833922-7512e14c-5399-11e8-907c-94a1a7be28e4.png)

**Comment by andywu123** [comment]
implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked its done
