### ISSUE TITLE
Without Filling Mandatory Fields I Can Save the Information - Create Witness

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#11]
In Create Witness i can save the information without filling mandatory fields. It should not save without filling mandatory field. 
![2018-05-09 15_15_57-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/39834764-004fe91a-539c-11e8-98e5-c60045a6bfe3.png)

**Comment by andywu123** [comment]
implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked Its Done.
