### ISSUE TITLE
Date Of Birth Field Has Time on It

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#12]
In Create Vehicle page, Date Of Birth Field has time in it. Time should be removed. 
![2018-05-09 16_31_04-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/39838314-12993c1a-53a7-11e8-8ede-563102b8796a.png)

**Comment by andywu123** [comment]
implemented, available in next release

**Comment by ChanduR123** [comment]
Checked Its Done.
