### ISSUE TITLE
Home Phone Number Field text box and Arrow keys in it

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#13]
In create vehicle page home phone number has arrow keys in it. need to be removed. 
![2018-05-09 16_42_06-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/39839097-16906260-53a9-11e8-82b9-851e328b4bbe.png)

**Comment by andywu123** [comment]
implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked its done.
