### ISSUE TITLE
Edit page, Field Zip-code Has Arrow Keys

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#14]
In vehicle info edit page zip code field has arrow keys m
![2018-05-10 13_40_13-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 8](https://user-images.githubusercontent.com/39100298/39884534-2cdc061e-5458-11e8-95c0-303ad0a8f449.png)
ay be not need.

**Comment by andywu123** [comment]
implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked its done.
