### ISSUE TITLE
Not Able to Change Time

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#15]
In create charges page, Trial Time field not able to change the time.
![2018-05-10 13_58_03-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 8](https://user-images.githubusercontent.com/39100298/39885400-7e53ffae-545a-11e8-83ca-89f9464eae2d.png)

**Comment by andywu123** [comment]
Implemented, will be available in the release of next week

**Comment by ChanduR123** [comment]
Time should be changed to 12 hrs not 24 hrs. Its hard to locate exact time. 
![2018-05-16 11_37_34-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/40127549-a036e65c-58fd-11e8-8370-03972fd3b85a.png)

**Comment by andywu123** [comment]
Implemented, will be available in the release

**Comment by ChanduR123** [comment]
Checked its done.
