### ISSUE TITLE
Can Improve Alignment For Signature 

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#16]
The alignment of signature button are not properly set
![2018-05-10 14_06_05-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 8](https://user-images.githubusercontent.com/39100298/39885813-97810642-545b-11e8-8065-b9b79e8d057a.png)
.

**Comment by andywu123** [comment]
want to hear more from Singh

**Comment by ChanduR123** [comment]
Checked its done.
