### ISSUE TITLE
Highlight color on cases Background

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#2]
When i put my mouse pointer on cases list the background color is 2 colors for case. Can we change color to single color. 

![2018-05-09 13_22_20-dpw-cisweb-tst_mvar_test_home_index](https://user-images.githubusercontent.com/39100298/39829369-35346760-538c-11e8-8e90-3e23c423175b.png)

**Comment by andywu123** [comment]
implemented, available in next release

**Comment by ChanduR123** [comment]
Checked its done.
