### ISSUE TITLE
Commit button should change color

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#21]
In sign and draw page after saving signature and draing the image, down the commit button color should change from red to green after commit. Need to be changed. 
![2018-05-16 11_22_29-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 3](https://user-images.githubusercontent.com/39100298/40126531-89479ad8-58fb-11e8-8ee5-7ea663e4559b.png)

**Comment by andywu123** [comment]
implemented, available in next release

**Comment by ChanduR123** [comment]
need to change color for signature page for commit button

**Comment by ChanduR123** [comment]
Checked its done.
