### ISSUE TITLE
Remove the Delete Symbol

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#22]
On main page please remove the delete symbol on the close report. 
![2018-05-16 14_57_14-dpw-cisweb-tst_mvar_test_home_index](https://user-images.githubusercontent.com/39100298/40137901-8048fe7c-5919-11e8-89f4-2f2182f9184a.png)

**Comment by andywu123** [comment]
Updates are made, will be available in next release.

**Comment by ChanduR123** [comment]
Checked its done
