### ISSUE TITLE
First Come First Serve the new cases

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#23]
on the main page if new case is created after saving it should on the top. First come first serve model. 
![2018-05-16 15_01_18-dpw-cisweb-tst_mvar_test_home_index](https://user-images.githubusercontent.com/39100298/40138141-0f85b486-591a-11e8-8bb9-f146c5e79259.png)
cases can be ascending or descending.

**Comment by andywu123** [comment]
Updates are made, will be available in next release.

Will be sorted by create date of the case

**Comment by ChanduR123** [comment]
checked its done
