### ISSUE TITLE
Search Option unable to search closed Report

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#24]
Please you need to work on search option. We cant see the closed reports. 
![2018-05-16 15_06_34-dpw-cisweb-tst_mvar_test_home_index](https://user-images.githubusercontent.com/39100298/40138480-c37d5444-591a-11e8-800f-8a497df47a67.png)

**Comment by andywu123** [comment]
updated, but a  search box should be added  sooner or later

**Comment by ChanduR123** [comment]
I checked its done.
