### ISSUE TITLE
Remove the more pop up windows

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#25]
After writing all the information in the page. If we click save button it shows pop up windows to confirm it. Try to make it simple for the field persons. Keeping one save buttons without pop up windows.

**Comment by andywu123** [comment]
all the notifications for local save actions are removed. Notifications for delete actions and sync functions are kept because they are more sensitive

**Comment by ChanduR123** [comment]
I cant see changes which you made.

**Comment by andywu123** [comment]
Hi Chandu, I will push them in next release. Should be OK on tomorrow.

**Comment by ChanduR123** [comment]
Still i see pop window for signature 
![2018-05-31 13_27_03-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 15](https://user-images.githubusercontent.com/39100298/40797549-871c8930-64d6-11e8-8599-56c8843aad57.png)

**Comment by ChanduR123** [comment]
Checked its done.
