### ISSUE TITLE
Change the Time and Date Field 

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#6]
In create new case time and date field should be updated. For **Exact Date and Hour of Accident** field. 
![2018-05-09 13_50_08-dpw-cisweb-tst_mvar_test_home_createaccidentreport](https://user-images.githubusercontent.com/39100298/39830698-3751424e-5390-11e8-85f4-acf6a0187abf.png)

**Comment by andywu123** [comment]
implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked Its done
