### ISSUE TITLE
Occupant Age has Negative Numeric Numbers 

### ISSUE THREAD

**Issue by ChanduR123** [ChanduR123/DPW_MVAR#8]
When you go to edit page, in occupant info there is field called **Occupant Age** the negative numeric
![2018-05-09 14_04_32-dpw-cisweb-tst_mvar_test_home_editaccidentreport_caseid 9](https://user-images.githubusercontent.com/39100298/39831622-0f4b3572-5393-11e8-8f12-6c7d3af3907d.png)
 should be removed for age.

**Comment by andywu123** [comment]
min age is 16, implemented, will be available in next release

**Comment by ChanduR123** [comment]
Occupant Age should have max number to Limit.

**Comment by andywu123** [comment]
max age is 200, implemented, will be available in next release

**Comment by ChanduR123** [comment]
Checked its done.
